export interface ActivationLineType {
  id: string;
  user_id: string;
  status: string;
  zipcode: string | null;
  number: string;
  imei: string;
  iccid: string | null;
  enrollment_id: string | null;
  activation_code: string | null;
  customer_id: string | null;
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  address1: string | null;
  address2: string | null;
  city: string | null;
  state: string | null;
  address_zipcode: string | null;
  is_port: number;
  port_first_name: string | null;
  port_last_name: string | null;
  port_address1: string | null;
  port_address2: string | null;
  port_city: string | null;
  port_state: string | null;
  port_zipcode: string | null;
  port_number: string | null;
  port_account_number: string | null;
  port_pin: string | null;
  port_ssn: string | null;
  sim_id: string | null;
  activation_order_id: string;
  type: string;
  parent_id: string | null;
  activation_plan_id: string | null;
  plan_id: string | null;
  price: number;
  created_at: string;
  updated_at: string;
  password: string | null;
  end_date: string | null;
  auto_pay: number;
  suspended_at: string | null;
  restored_at: string | null;
  deactivated_at: string | null;
  port_enrollment_id: string | null;
  source: string;
  dummy: number;
  test: number;
  external_id: string | null;
  reference: string | null;
  platform: string;
  platform_version: string | null;
  reactivated_at: string | null;
  activation_plan_offer_id: string | null;
  order_type: string;
}

export interface Sim {
  id: string;
  iccid: string;
  status: string;
  user_id: string;
  lpa: string;
  activation_code: string;
  smdp_address: string;
  imei: string;
  enrollment_id: string | null;
  type: string;
  created_at: string;
  updated_at: string;
  activation_line_id: string | null;
  active: number;
  batch: string | null;
  vendor: string | null;
  reference: string | null;
  dummy: number;
}

export interface LineHistoryType {
  id: string;
  user_id: string;
  status: string;
  zipcode: string;
  number: string;
  imei: string;
  iccid: string | null;
  enrollment_id: string | null;
  activation_code: string | null;
  customer_id: string | null;
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  address1: string | null;
  address2: string | null;
  city: string | null;
  state: string | null;
  address_zipcode: string | null;
  is_port: number;
  port_first_name: string | null;
  port_last_name: string | null;
  port_address1: string | null;
  port_address2: string | null;
  port_city: string | null;
  port_state: string | null;
  port_zipcode: string | null;
  port_number: string | null;
  port_account_number: string | null;
  port_pin: string | null;
  port_ssn: string | null;
  sim_id: string | null;
  activation_plan_id: string | null;
  plan_id: string | null;
  price: number;
  created_at: string;
  updated_at: string;
  password: string | null;
  port_enrollment_id: string | null;
  message: string | null;
  source: string;
  dummy: number;
  test: number;
  external_id: string | null;
  reference: string | null;
  platform: string;
  platform_version: string | null;
  activation_plan_offer_id: string | null;
  order_type: string;
  subscription_id: number;
  activation_line: ActivationLineType;
  line_status: string;
  has_active_line: boolean;
  sim: Sim;
}

export interface LineHistoryResponseType {
  status: boolean;
  data: LineHistoryType[];
}
